[package]
name = "num-fuzz"
version = "0.0.1"
authors = ["copied from rust-bitcoin"]
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
honggfuzz = { version = "0.5" }
num = { path = ".." }

[[bin]]
name = "fuzz"
path = "fuzz.rs"
